### PR TITLE
Add pricing page

### PR DESCRIPTION
**Pull request by makoto**
I put the link on footer. It's up for discussion whether we should put that on header or not.

### CODE REVIEW

**Comment by hiddentao** [comment]
Build failed

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr92-app-wearekickback.surge.sh

**Comment by hiddentao** [comment]
We should have link in top nav bar for sure.

**Comment by hiddentao** [comment]
Also, on homepage we should have Pricing + Guide links - at present we only have Events

**Comment by makoto** [comment]
@hiddentao 

Do you want to have "Pricing|Guide|Events" or should Pricing be part of Guide? I am guessing you meant for the former.

**Comment by hiddentao** [comment]
Should be Events Pricing Guide


--
Ramesh Nair


Director
HiddenTao Ltd (UK company no. 6807289)


http://hiddentao.com
https://github.com/hiddentao
https://www.linkedin.com/in/hiddentao

**Comment by makoto** [comment]
@hiddentao added a few sentences.

https://github.com/wearekickback/app/pull/92/commits/b527fecc6fbc8dc10993dae237f96393004353ea

One is to make sure that people are clear that who is paying, and another sentence is responding to most asked questions in terms of pricing (I even got asked last night by our client). Let me know if we need rewording.

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr92-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr92-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr92-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr92-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr92-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr92-app-wearekickback.surge.sh

**Pull request merged**
