### PR TITLE
Add event specific metatag

### PR DESCRIPTION
**Pull request by makoto**

### CODE REVIEW

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr103-app-wearekickback.surge.sh

**Comment by makoto** [comment]
It looks like dynamically injecting metatag does not work. I tested on medium , slack and this site but none of them worked.

https://www.heymeta.com/url/pr103-app-wearekickback.surge.sh/event/0x66e374a6300dd9443cfbb3fc2c4e73f1d6dab1f8

Maybe we need to render at server side?

**Review by hiddentao — DISMISSED** [review]

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr103-app-wearekickback.surge.sh

**Comment by makoto** [comment]
Probably the only way we can do in the current  architecture is to have proxy service in front of our app  and let it redirect if it's not crawler https://medium.com/@miltonakash/seo-and-rich-sharing-for-single-page-application-spa-58a3725dcb9

**Pull request closed without merging**
