### PR TITLE
Deploy any ERC20 support to live

### PR DESCRIPTION
**Pull request by makoto**

### CODE REVIEW

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr263-app-wearekickback.surge.sh

**Comment by TomAFrench** [comment]
Something I just noticed from this deployment is that the Approve message isn't great in the case where the user hasn't allowed access to metamask. It complains about insufficient balance despite not knowning what the user's balance is.



It's probably worth adding a little bit of logic adding a `get_accounts` check to replace that with a "Log in / enable metamask to RSVP" button  in that case.

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr263-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr263-app-wearekickback.surge.sh

**Pull request merged**
