### PR TITLE
Added support to add to calendar feature

### PR DESCRIPTION
**Pull request by eswarasai**
### Description
- [x] Added support to add to calendar for Google, Yahoo, Outlook and iCal

### Screenshots
Screenshot 2019-10-07 at 1 53 15 PM

Screenshot 2019-10-07 at 1 53 40 PM

Fixes: #185

### CODE REVIEW

**Comment by eswarasai** [comment]
@makoto - I couldn't leverage the either packages available out there. Hence had to re-use most of the lib code in this repo which helps us to customize the things w.r.t. design. I need some help with the styling of the Add to Calendar Modal list with icons. Can you please guide me here? Thanks!

**Comment by jefflau** [comment]
Hi @eswarasai,

We're both at devcon so it might be a little slower to get your PR through. I think the styling generally looks good. For bonus points you could add some of the calendar icons for each calendar such as:

https://collegeinfogeek.com/wp-content/uploads/2016/08/Google_Calendar_Logo.png

Let me check how it looks

**Comment by jefflau** [comment]
Hi @eswarasai,

I just had a look at the demo and it looks great. Could we change the download file name to the name of the event instead of 'download.ics'? And I think we are ready to merge if we can get that done

Jeff

**Comment by eswarasai** [comment]
@jefflau - Sure, I can take care of that quickly. Give me couple of minutes to update the PR.

Re: Calendar icons, I see that most of the icons are custom designed matching the theme of the website. Hence I haven't added any and mentioned the same in the original PR comments

**Comment by eswarasai** [comment]
@jefflau - Updated the PR. Let me know if anything else needs to be handled here. Thanks!

cc: @makoto

**Pull request merged**
