### PR TITLE
Add a web3read that goes direct to infura

### PR DESCRIPTION
**Pull request by jefflau**
## Issue number
https://github.com/wearekickback/app/pull/256 requires a web3 read from infura just in case the user is not correct to the right network

## List of features added/changed
Added in a web3 read function. Refactored out the network function to be used in both places

## How Has This Been Tested?
Has not been tested

@TomAFrench I've added this function to be used on web3 read only functions like the token symbol so we don't get that error whilst querying the user's web3 rather than the network we expect it to be on

### CODE REVIEW

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr258-app-wearekickback.surge.sh

**Comment by TomAFrench** [comment]
ok, I'll just copy paste this change into #256 and test

**Comment by makoto** [comment]
You need a bit more than copy&paste. You have to make use of `getWeb3Read` so that it receive correct token info even when not connected to the correct network (rather than showing "no token info available).

**Comment by TomAFrench** [comment]
Oh for sure, I took linking it up to the existing code as implied.

**Comment by makoto** [comment]
This is merged into different PR hence closing

**Pull request closed without merging**
