### PR TITLE
Add custom loader and fix all events query

### PR DESCRIPTION
**Pull request by jefflau**
@hiddentao There's a bug with SafeQuery when it's loading it doesn't seem to render loading and it DOES render the children. I couldn't figure out why and I just used the normal Query, which I didn't think was much extra code. Maybe you look into it if you have time

### CODE REVIEW

**Comment by hiddentao** [comment]
Will look at this later, but please fix the build first.

**Comment by jefflau** [comment]
Whoops sorry, build should be fixed now

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr62-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr62-app-wearekickback.surge.sh

**Pull request merged**
