### PR TITLE
Torus Integration

### PR DESCRIPTION
**Pull request by YZhenY**
Description
Integration with torus login, we love kickback!

List of features added/changed
OAuth logins and more

How Has This Been Tested?
WIP

### CODE REVIEW

**Comment by jefflau** [comment]
Working on my end. Can you take a look @makoto, and if so we should push Authereum to fix and/or remove the Authereum part before merging

**Comment by makoto** [comment]
How did you guys test? Did you only test sign in or actually try to RSVP as well? I pulled this PR in my local and pointed to mainnet but it's throwing the following error when navigated to an event page and refresh the page AFTER signed into Tor.us with this error.

Screenshot 2020-01-07 at 21 21 20


When I deployed the branch to https://pr228-app-wearekickback.surge.sh, I was able to login as makotorus but I get a blank page when I refresh the page 

Screenshot 2020-01-07 at 21 35 57

**Comment by makoto** [comment]
When logged in as Authereum , it shows Authereum Logo underneath user profile image (which style seems broken) and I don't see the similar link for Torus.

Screenshot 2020-01-07 at 21 41 37

**Comment by makoto** [comment]
Also, do you guys have any test env so that we can test in either Kovan or Rinkeby?

**Comment by jefflau** [comment]
@makoto I checked locally by cloning his repo, yarn and the yarn start. I only created an account called jefflau_torus. I didn't check more than that so far since it's on mainnet. It would be useful @YZhenY if we had a test environment so I can freely check creating events without it costing us money

**Comment by chaitanyapotti** [comment]
Hi, we do support all test environments including rinkeby, ropsten, kovan, goerli etc.

**Comment by YZhenY** [comment]
the integration should just work on any rpc testnet @makoto @jefflau. Its the env though, if we pass in a specific testnet env should just work.

**Comment by jefflau** [comment]
@YZhenY I'll have a look to see if I can get it working on Kovan. Is there a way we can show a link to torus to top-up some Dai/ETH if they don't have any?

**Comment by YZhenY** [comment]
https://docs.tor.us/api-reference/topup, yes you can directly call the topup API

**Pull request closed without merging**
