### PR TITLE
Cutoff

### PR DESCRIPTION
**Pull request by jefflau**

### CODE REVIEW

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr175-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
Shall we change the rule section from

"Any no-shows lose their commitment, which will be split amongst the attendees."
to
"Any no-shows or late shows who did not turn up by **Arrive by** lose their commitment, which will be split amongst the attendees."

**Comment by jefflau** [comment]
Add this to a separate ticket

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr175-app-wearekickback.surge.sh

**Pull request merged**
