### PR TITLE
Support erc20

### PR DESCRIPTION
**Pull request by makoto**
This is a copy of https://github.com/wearekickback/app/pull/239 to automaticallly deploy

### CODE REVIEW

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr246-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr246-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr246-app-wearekickback.surge.sh

**Comment by makoto** [comment]
Close this to avoid duplicate

**Pull request closed without merging**
