### PR TITLE
Add Sign in button on Hamburger dropdown

### PR DESCRIPTION
**Pull request by makoto**
To fix this. https://trello.com/c/MGjjsTq0/287-mobile-mode-does-not-have-login-profile-page

This is how it looks after the change.

screenshot 2019-02-28 at 11 16 10
screenshot 2019-02-28 at 11 16 41

### CODE REVIEW

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr94-app-wearekickback.surge.sh

**Review by hiddentao — CHANGES_REQUESTED** [review]
I think Sign up / Profile avatar should come first in the menu list

**Comment by makoto** [comment]
@hiddentao done. Better?

screenshot 2019-02-28 at 14 45 34

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr94-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr94-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr94-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr94-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr94-app-wearekickback.surge.sh

**Review by hiddentao — APPROVED** [review]

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr94-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr94-app-wearekickback.surge.sh

**Pull request merged**
