### PR TITLE
Disable RSVP button with insufficient ETH

### PR DESCRIPTION
**Pull request by TomAFrench**
## Description

I've fixed a couple of inconsistencies on the RSVP button when using ETH

## List of features added/changed

- Hides Approve button for ETH by fixing isToken check
- Disables RSVP button if ether balance is too low
- Adds handling for ETH in getTokenAllowance (returns `{balance: balance, allowance: balance}`)

## How Has This Been Tested?

I've checked the appearance for when I have enough / not enough ETH to ensure that it displays correctly. Also for another token to ensure that they are unaffected.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by jefflau** [comment]
Hey @TomAFrench!

Thanks for this. We really appreciate it. Code looks good to me. @makoto can you check it works as expected?

**Comment by makoto** [comment]
Hi, @TomAFrench 

Just comparing the new version (left) and existing version (right) and lgtm.

Thank you so much for your contribution!

Screenshot 2020-01-17 at 19 05 23

If you really want to make it consistent, you can also display message like DAI page.

Screenshot 2020-01-17 at 19 18 51

**Comment by makoto** [comment]
umm, I just merged dev and CI seems failing

**Comment by TomAFrench** [comment]
@makoto yup, this and #256 seem to be treading on each other's toes. It should work now.

**Comment by TomAFrench** [comment]
@makoto Ohhhhh, sorry just realised what you meant. I thought you were talking about CI on this PR

**Comment by TomAFrench** [comment]
@makoto Could you maybe just rerun Travis? I've had it fail in the past and it just needs a rerun

**Comment by TomAFrench** [comment]
@makoto It's a node version issue. You're using v12.13.1 on zeit but dubnium on travis so when you deploy to zeit then the build fails there which in turn kills travis.

**Pull request merged**
