### PR TITLE
Onboardjs tom

### PR DESCRIPTION
**Pull request by makoto**
#279

### CODE REVIEW

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr280-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr280-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr280-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr280-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr280-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr280-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr280-app-wearekickback.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr280-app-wearekickback.surge.sh

**Comment by makoto** [comment]
Duplicate PR

**Pull request closed without merging**
